name: Build (Qt)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: jurplel/install-qt-action@v3
      with:
        arch: 'gcc_64'
        archives: 'icu qtbase qtmultimedia qtgamepad'
    - name: Build
      run: qmake && make
